baseURL = "https://www.ethan-young.com/"
languageCode = "en-us"
title = "ESY"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[Params]
  RSSLink = "/index.xml"
  author = "Ethan S. Young" # add your company name
  github = "https://github.com/ethan-young" # add your github profile name
  email = "young.ethan.scott@gmail.com"
  google_scholar = "https://scholar.google.com/citations?hl=en&user=DzFMpnYAAAAJ"
  osf = "https://osf.io/vr5yx"
  research_gate = "https://www.researchgate.net/profile/Ethan_Young3"
  university = "Utrecht University"
  city = "Utrecht"
  country = "the Netherlands"
  job = "Postdoctoral Researcher"
  degree = "Ph.D."

# Top Menu
# Ethan 
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 2
[[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3
## Academic Research
[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 11
[[menu.main]]
    name = "Code"
    url = "/code/"
    weight = 12
## Skills Portfolio
[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 22
[[menu.main]]
    name = "Visualizations"
    url = "/portfolio/visualizations/"
    weight = 24
[[menu.main]]
    name = "Shiny Applications"
    url = "/portfolio/shiny-apps/"
    weight = 25
[[menu.main]]
    name = "Behavioral Tasks"
    url = "/portfolio/tasks/"
    weight = 26

#[[menu.main]]
#    name = "Archive"
#    weight = 9
#    url = "/Archive/"
#    parent = "Code"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
