baseURL = "/"
languageCode = "en-us"
title = "ESY"

[Params]
  RSSLink = "/index.xml"
  author = "Ethan S. Young" # add your company name
  github = "https://github.com/ethan-young" # add your github profile name
  email = "young.ethan.scott@gmail.com"
  google_scholar = "https://scholar.google.com/citations?hl=en&user=DzFMpnYAAAAJ"
  osf = "https://osf.io/vr5yx"
  research_gate = "https://www.researchgate.net/profile/Ethan_Young3"
  university = "Utrecht University"
  city = "Utrecht"
  country = "The Netherlands"
  job = "Postdoctoral Researcher"
  degree = "Ph.D."

[[menu.main]]
    name = "Work"
    weight = 10
[[menu.main]]
    name = "Sandbox"
    weight = 20

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    parent = "Work"
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    parent = "Sandbox"
[[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    parent = "Work"
[[menu.main]]
    name = "CV"
    url = "/cv/"
    parent = "Work"
[[menu.main]]
    name = "Learning"
    url = "/resources/"
    parent = "Sandbox"
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

#[[menu.main]]
#    name = "Publications"
#    weight = 10
#    url = "/publications/"
#[[menu.main]]
#    name = "Posts"
#    weight = 20
#    url = "/posts/"
#[[menu.main]]
#    name = "Portfolio"
#    weight = 30
#    url = "/portfolio/"
#[[menu.main]]
#    name = "CV"
#    weight = 40
#    url = "/cv/"
#[[menu.main]]
#    name = "Resources"
#    weight = 50
#    url = "/resources/"
#[[menu.main]]
#    name = "About"
#    weight = 60
#    url = "/about/"

#[[menu.main]]
#    name = "Archive"
#    weight = 50
#    url = "/Archive/"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "^cv-pdf\\.Rmd$"]