---
title: "Resources"
description:  "A list of resources I have found valuable."
draft: false
tocbot: false
---

```{r, echo=F,message=F,warning=F}
library(tidyverse)
library(glue)
library(htmltools)
library(readxl)

resources <- read_excel("../../data/resources.xlsx")
nav_pill <- resources %>% pull(Purpose) %>% unique()
```

<div class="uk-child-width-1-1@s" uk-grid>
<div>
<div uk-grid>

```{r echo=F, message=F, warning=F, results='asis'}
HTML(
  "<div class='uk-width-auto@m'>",
  "<ul class = 'uk-tab-left' uk-tab = 'connect: #component-tab-left; animation: uk-animation-fade'>",
  map_chr(nav_pill, function(x){
    HTML(
      "<li><a href = '#'>",x,"</a></li>"
    )
  }) %>% unlist() %>% paste(collapse = ""),
  "</ul>",
  "</div>"
)
```

```{r echo=F, message=F, warning=F, results='asis'}
HTML(
  "<div class='uk-width-expand uk-padding-remove-top'>",
  "<ul id = 'component-tab-left' class = 'uk-switcher uk-margin'>",
  map_chr(nav_pill, function(x){
    HTML(
      "<li>",
      resources %>% 
        filter(Purpose == x) %>% 
        mutate(
          Resource = paste0("<a href = '", url,"'>", Resource,"</a>")
        ) %>% 
        select(Resource, Description) %>% 
        knitr::kable(
            format = "html",
            escape = F,
            table.attr = "class=\"uk-table uk-table-small uk-table-divider\""
        ),
      "</li>"
    )
  }) %>% unlist() %>% paste(collapse = ""),
  "</ul>",
  "</div>"
)
```

</div>
</div>
</div>