---
title: "About"
draft: false
tocbot: true
---

### About Ethan

I received my doctorate in 2019 from the Department of Psychology at the University of Minnesota. Soon after, I flew across the Atlantic to the Netherlands where I am currently a postdoctoral researcher in the Department of Psychology at Utrecht University. I am broadly interested in how early life experiences and environments shape cognition, behavior, physiology, and health. More specifically, I study how adverse environments shape mental abilities that are useful under stressful conditions. I also look at how stress across the lifespan impacts stress physiology and biological health outcomes.

### About this Site

I built this site to create a semi-permanent place to store my work and ideas. You can find my standard academic content, such as my [cv](../cv/) and [publications](../publications/). In my [posts](../posts/) section, I document solutions to various problems/challenges I encounter in my research. These usually involve a brief explanation of the topic and some R-code I wrote to address it. I primarily write them for "future me"; I like having a place to revisit problems, borrow code, and remember what "past-me" was thinking.

This site was built using [Hugo](https://gohugo.io), [blogdown](https://bookdown.org/yihui/blogdown), and [UIkit](https://getuikit.com/). Hugo is a programming language for making static websites and takes adantage of a templating ecosystem. Blogdown is a wonderful R-package for using R markdown and Hugo together to make websites/blogs. The advantage of blogdown is that you can incorporate and run R-code to dynamically create pages and content. UIkit is an open source front-end library of pre-built tools and web components. I adapted the UIkit theme to my taste. The source code for the site can be found on [github](https://github.com/ethan-young/website).

<script>
$(document).ready(function(){
  $("article a").each(function(){
    $(this).attr("target", "_blank");
  });
});
</script>